### ISSUE TITLE
"ecoli.txt"

### ISSUE THREAD

**Issue by Jeni05** [katholt/srst2#132]
Hey, I've been making my way through the worked example and I have also tried the script with my own sequences. But every time I try running the script:
"srst2 --input_pe ERR024070*.fastq.gz --output shigella1 --log --save_scores --mlst_db Escherichia_coli#1.fasta --mlst_definitions ecoli.txt --gene_db ARGannot.fasta" 
I get an output that looks promising, but then an error message: 
"[Errno 2] No such file or directory: 'ecoli.txt'" 
I then get a "command not found" message when I try to look at any result files. 
I've tried everything I can find online, but each time I'm met with the same error message. I am a very new at using the command line so I know there is likely something basic that I am missing. Any advice would be great, thanks :)

**Comment by scwatts** [comment]
Hi, thanks for your interest in srst2! The error looks to be caused by a missing mlst definitions file.

I can see that PubMLST has recently updated the naming scheme for their databases (e.g. the _E. coli_ mlst definitions file has been renamed from `ecoli.txt` to `profiles_csv`), which means the worked example is out of date.

Changing `--mlst_definitions ecoli.txt` to `--mlst_definitions profiles_csv` in the command you provided should solve this error. I've also updated the basic usage example in the README.md to reflect the changes  PubMLST database naming.
