### ISSUE TITLE
Error with bowtie

### ISSUE THREAD

**Issue by edgarom** [katholt/srst2#57]
Hi...

I have problem when try to run the command srst2  

Input files DNA, FASTA:
  salmonella.fasta
Error: could not open salmonella.fasta
Total time for call to driver() for forward index: 00:00:00
Error: Encountered internal Bowtie 2 exception (#1)
Command: bowtie2-build --wrapper basic-0 salmonella.fasta salmonella.fasta 
Traceback (most recent call last):
  File "/usr/local/bin/srst2", line 9, in <module>
    load_entry_point('srst2==0.1.7', 'console_scripts', 'srst2')()
  File "/usr/local/lib/python2.7/dist-packages/srst2/srst2.py", line 1604, in main
    bowtie_index(args.mlst_db) # index the MLST database
  File "/usr/local/lib/python2.7/dist-packages/srst2/srst2.py", line 154, in bowtie_index
    run_command([bowtie_build_exec, fasta, fasta])
  File "/usr/local/lib/python2.7/dist-packages/srst2/srst2.py", line 134, in run_command
    raise CommandError({"message": message})
srst2.srst2.CommandError: {'message': "Command 'bowtie2-build salmonella.fasta salmonella.fasta' failed with non-zero exit status: 1"}

as I can resolve this error?....

I have a second question, if I have four files form miseq and nexseq ( 2file_R1 and 2file_R2 ) belonging to the same sample as I can gather the reads for the same result?

**Comment by rrwick** [comment]
I know it's been a while, but I thought I'd chime in in case you (or anybody else) are still dealing with these issues.

The first error seems to be with the bowtie2-build command `bowtie2-build salmonella.fasta salmonella.fasta`. It would seem that `salmonella.fasta` either doesn't exist or you don't have permission to read it. You could try running that same command manually to see if `bowtie2-build` works outside of SRST2. Failing that, reinstalling/upgrading Bowtie and SRST2 is worth a shot, as there have been releases of both since you posted this issue.

Regarding your second question, it is possible to have multiple read sets for one strain by using `--merge_paired`. This option makes SRST2 assume that _all_ reads in the run are from the same sample. So it's not possible to run SRST2 on your four-file set and others at the same time - you'd have to run them separately and then merge the results after they're all done.

**Comment by TreeT2** [comment]
Hi All,
Ive recently encountered this error when using slurm srst2.  I never had an issue when using srst2 alone. 
Im using samtools/0.1.18 and bowtie/2.2.9 and python/2.7.5. Not sure what the issue is. Any suggestions?
