### ISSUE TITLE
assembled contigs as input files for srst2?

### ISSUE THREAD

**Issue by MostafaYA** [katholt/srst2#77]
Hi, 
Is that possible for srst2 to take the assembled contigs as input files (for example, contigs downloaded from NCBI and the raw data are not available)? If yes, what argument should be used?

**Comment by rrwick** [comment]
Sorry, but SRST2 cannot take assemblies as input. Instead you would need to use something like BLAST to look for genes in your assemblies.

Having run into this same issue myself, I made a tool which uses BLAST to search for genes in an SRST2 database and produce an SRST2-like output: [SRST2-table-from-assemblies](https://github.com/rrwick/SRST2-table-from-assemblies). You're welcome to give it a try!

A few things to note:
* This tool only copies the gene database functionality of SRST2, not the MLST functionality. If you need to do MLST on assemblies, I'd recommend this tool: https://github.com/tseemann/mlst
* This tool can put a `*` next to a gene match (indicating an inexact match), but it _cannot_ put a `?` like SRST2 can. This is because SRST2 uses read mapping details to determine uncertainty - something that isn't possible with assemblies.
* The output of this tool can be combined with regular SRST2 results using the process described [here](https://github.com/katholt/srst2#compile-results-from-completed-runs).

Hope that helps!
